#!/bin/bash

echo ' fi  >> screenSYS ' 
echo ' ... >> cd '
echo ' na  >> nano текстовый редактор '
echo ' se  >> рвспаковать архив(tar и др.) ' 
echo '############################################'
echo ' py  >> pacaur -Syu << обновлене пакетов из AUR  '
echo ' pi  >> pacaur -S << установка пакета из AUR '   
echo '############################################'
echo ' s   >> sudo '
echo ' ss  >> sudo su ' 
echo '############################################'
echo ' del >> sudo pacman -R << удаление пакета без зависимостей '
echo ' ap  >> sudo pacman -S << установка пакета '
echo ' sy  >> sudo pacman -Sy синхранизация  '
echo ' yy  >> sudo pacman -Syyu << обновление системы  '
echo '############################################'
echo '  q  >> выйти из терминала ' 
echo ' cli >> очистить окно терминала '
echo ' off >> выключить ПК '
echo ' re  >> перезагрузить ПК '
	
